/**
 * Fetches all Paris 2024 Olympic football matches from the official schedule API
 * and writes them to src/data/paris2024-seed.ts.
 *
 * Run with: npx tsx scripts/generate-seed.ts
 */
import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { scrapeOlympicSchedule } from '@/lib/scraper'

async function main() {
  console.log('Fetching Paris 2024 Olympic football schedule…')
  const { matches } = await scrapeOlympicSchedule()
  console.log(`Total: ${matches.length} football matches`)

  const content =
    `import { Match } from '@/types/match'\n\n` +
    `// Generated by scripts/generate-seed.ts — do not edit manually.\n` +
    `// Source: https://stacy.olympics.com/srm/data/oly/schedule/day/ENG/{date}.json\n` +
    `export const PARIS_2024_EVENTS: Match[] = ${JSON.stringify(matches, null, 2)}\n`

  const outPath = resolve(process.cwd(), 'src/data/paris2024-seed.ts')
  writeFileSync(outPath, content, 'utf-8')
  console.log(`Written → ${outPath}`)
}

main().catch((e) => {
  console.warn('[generate-seed] Failed to fetch live data:', e?.message ?? e)
  console.warn('[generate-seed] Existing seed will be used. Run manually to retry.')
  process.exit(0)
})
