import { Match } from '@/types/match'

// Generated by scripts/generate-seed.ts — do not edit manually.
// Source: https://stacy.olympics.com/srm/data/oly/schedule/day/ENG/{date}.json
export const PARIS_2024_EVENTS: Match[] = [
  {
    "id": "FBLMTEAM11------------GPB-000100--",
    "sport": "Football",
    "discipline": "Men's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Geoffroy-Guichard Stadium",
      "city": "Saint-Etienne"
    },
    "kickoff": "2024-07-24T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Argentina",
      "away": "Morocco"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPC-000100--",
    "sport": "Football",
    "discipline": "Men's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-07-24T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Uzbekistan",
      "away": "Spain"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPA-000200--",
    "sport": "Football",
    "discipline": "Men's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Nice Stadium",
      "city": "Nice"
    },
    "kickoff": "2024-07-24T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Guinea",
      "away": "New Zealand"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPC-000200--",
    "sport": "Football",
    "discipline": "Men's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-07-24T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Egypt",
      "away": "Dominican Republic"
    },
    "score": {
      "home": 0,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPB-000200--",
    "sport": "Football",
    "discipline": "Men's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-07-24T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Iraq",
      "away": "Ukraine"
    },
    "score": {
      "home": 2,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPD-000200--",
    "sport": "Football",
    "discipline": "Men's Group D",
    "round": "Group Stage",
    "venue": {
      "name": "Bordeaux Stadium",
      "city": "Bordeaux"
    },
    "kickoff": "2024-07-24T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Japan",
      "away": "Paraguay"
    },
    "score": {
      "home": 5,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPA-000100--",
    "sport": "Football",
    "discipline": "Men's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-07-24T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "France",
      "away": "United States"
    },
    "score": {
      "home": 3,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPD-000100--",
    "sport": "Football",
    "discipline": "Men's Group D",
    "round": "Group Stage",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-07-24T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Mali",
      "away": "Israel"
    },
    "score": {
      "home": 1,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPA-000200--",
    "sport": "Football",
    "discipline": "Women's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Geoffroy-Guichard Stadium",
      "city": "Saint-Etienne"
    },
    "kickoff": "2024-07-25T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Canada",
      "away": "New Zealand"
    },
    "score": {
      "home": 2,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPC-000100--",
    "sport": "Football",
    "discipline": "Women's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-07-25T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Spain",
      "away": "Japan"
    },
    "score": {
      "home": 2,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPB-000200--",
    "sport": "Football",
    "discipline": "Women's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-07-25T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Germany",
      "away": "Australia"
    },
    "score": {
      "home": 3,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPC-000200--",
    "sport": "Football",
    "discipline": "Women's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "Bordeaux Stadium",
      "city": "Bordeaux"
    },
    "kickoff": "2024-07-25T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Nigeria",
      "away": "Brazil"
    },
    "score": {
      "home": 0,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPA-000100--",
    "sport": "Football",
    "discipline": "Women's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-07-25T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "France",
      "away": "Colombia"
    },
    "score": {
      "home": 3,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPB-000100--",
    "sport": "Football",
    "discipline": "Women's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Nice Stadium",
      "city": "Nice"
    },
    "kickoff": "2024-07-25T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "United States",
      "away": "Zambia"
    },
    "score": {
      "home": 3,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPB-000300--",
    "sport": "Football",
    "discipline": "Men's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-07-27T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Argentina",
      "away": "Iraq"
    },
    "score": {
      "home": 3,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPC-000400--",
    "sport": "Football",
    "discipline": "Men's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "Bordeaux Stadium",
      "city": "Bordeaux"
    },
    "kickoff": "2024-07-27T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Dominican Republic",
      "away": "Spain"
    },
    "score": {
      "home": 1,
      "away": 3,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPB-000400--",
    "sport": "Football",
    "discipline": "Men's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Geoffroy-Guichard Stadium",
      "city": "Saint-Etienne"
    },
    "kickoff": "2024-07-27T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Ukraine",
      "away": "Morocco"
    },
    "score": {
      "home": 2,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPC-000300--",
    "sport": "Football",
    "discipline": "Men's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-07-27T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Uzbekistan",
      "away": "Egypt"
    },
    "score": {
      "home": 0,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPA-000400--",
    "sport": "Football",
    "discipline": "Men's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-07-27T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "New Zealand",
      "away": "United States"
    },
    "score": {
      "home": 1,
      "away": 4,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPD-000300--",
    "sport": "Football",
    "discipline": "Men's Group D",
    "round": "Group Stage",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-07-27T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Israel",
      "away": "Paraguay"
    },
    "score": {
      "home": 2,
      "away": 4,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPA-000300--",
    "sport": "Football",
    "discipline": "Men's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Nice Stadium",
      "city": "Nice"
    },
    "kickoff": "2024-07-27T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "France",
      "away": "Guinea"
    },
    "score": {
      "home": 1,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPD-000400--",
    "sport": "Football",
    "discipline": "Men's Group D",
    "round": "Group Stage",
    "venue": {
      "name": "Bordeaux Stadium",
      "city": "Bordeaux"
    },
    "kickoff": "2024-07-27T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Japan",
      "away": "Mali"
    },
    "score": {
      "home": 1,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPA-000400--",
    "sport": "Football",
    "discipline": "Women's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-07-28T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "New Zealand",
      "away": "Colombia"
    },
    "score": {
      "home": 0,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPC-000400--",
    "sport": "Football",
    "discipline": "Women's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-07-28T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Brazil",
      "away": "Japan"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPB-000400--",
    "sport": "Football",
    "discipline": "Women's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Nice Stadium",
      "city": "Nice"
    },
    "kickoff": "2024-07-28T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Australia",
      "away": "Zambia"
    },
    "score": {
      "home": 6,
      "away": 5,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPC-000300--",
    "sport": "Football",
    "discipline": "Women's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-07-28T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Spain",
      "away": "Nigeria"
    },
    "score": {
      "home": 1,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPA-000300--",
    "sport": "Football",
    "discipline": "Women's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Geoffroy-Guichard Stadium",
      "city": "Saint-Etienne"
    },
    "kickoff": "2024-07-28T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "France",
      "away": "Canada"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPB-000300--",
    "sport": "Football",
    "discipline": "Women's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-07-28T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "United States",
      "away": "Germany"
    },
    "score": {
      "home": 4,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPC-000500--",
    "sport": "Football",
    "discipline": "Men's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-07-30T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Dominican Republic",
      "away": "Uzbekistan"
    },
    "score": {
      "home": 1,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPC-000600--",
    "sport": "Football",
    "discipline": "Men's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "Bordeaux Stadium",
      "city": "Bordeaux"
    },
    "kickoff": "2024-07-30T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Spain",
      "away": "Egypt"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPB-000500--",
    "sport": "Football",
    "discipline": "Men's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-07-30T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Ukraine",
      "away": "Argentina"
    },
    "score": {
      "home": 0,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPB-000600--",
    "sport": "Football",
    "discipline": "Men's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Nice Stadium",
      "city": "Nice"
    },
    "kickoff": "2024-07-30T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Morocco",
      "away": "Iraq"
    },
    "score": {
      "home": 3,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPA-000500--",
    "sport": "Football",
    "discipline": "Men's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-07-30T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "New Zealand",
      "away": "France"
    },
    "score": {
      "home": 0,
      "away": 3,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPA-000600--",
    "sport": "Football",
    "discipline": "Men's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Geoffroy-Guichard Stadium",
      "city": "Saint-Etienne"
    },
    "kickoff": "2024-07-30T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "United States",
      "away": "Guinea"
    },
    "score": {
      "home": 3,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPD-000500--",
    "sport": "Football",
    "discipline": "Men's Group D",
    "round": "Group Stage",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-07-30T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Israel",
      "away": "Japan"
    },
    "score": {
      "home": 0,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------GPD-000600--",
    "sport": "Football",
    "discipline": "Men's Group D",
    "round": "Group Stage",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-07-30T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Paraguay",
      "away": "Mali"
    },
    "score": {
      "home": 1,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPC-000500--",
    "sport": "Football",
    "discipline": "Women's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "Bordeaux Stadium",
      "city": "Bordeaux"
    },
    "kickoff": "2024-07-31T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Brazil",
      "away": "Spain"
    },
    "score": {
      "home": 0,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPC-000600--",
    "sport": "Football",
    "discipline": "Women's Group C",
    "round": "Group Stage",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-07-31T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Japan",
      "away": "Nigeria"
    },
    "score": {
      "home": 3,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPB-000500--",
    "sport": "Football",
    "discipline": "Women's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-07-31T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Australia",
      "away": "United States"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPB-000600--",
    "sport": "Football",
    "discipline": "Women's Group B",
    "round": "Group Stage",
    "venue": {
      "name": "Geoffroy-Guichard Stadium",
      "city": "Saint-Etienne"
    },
    "kickoff": "2024-07-31T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Zambia",
      "away": "Germany"
    },
    "score": {
      "home": 1,
      "away": 4,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPA-000500--",
    "sport": "Football",
    "discipline": "Women's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-07-31T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "New Zealand",
      "away": "France"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------GPA-000600--",
    "sport": "Football",
    "discipline": "Women's Group A",
    "round": "Group Stage",
    "venue": {
      "name": "Nice Stadium",
      "city": "Nice"
    },
    "kickoff": "2024-07-31T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Group Stage"
    },
    "teams": {
      "home": "Colombia",
      "away": "Canada"
    },
    "score": {
      "home": 0,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------QFNL000300--",
    "sport": "Football",
    "discipline": "Men's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-08-02T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "Morocco",
      "away": "United States"
    },
    "score": {
      "home": 4,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------QFNL000400--",
    "sport": "Football",
    "discipline": "Men's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-08-02T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "Japan",
      "away": "Spain"
    },
    "score": {
      "home": 0,
      "away": 3,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------QFNL000200--",
    "sport": "Football",
    "discipline": "Men's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-08-02T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "Egypt",
      "away": "Paraguay"
    },
    "score": {
      "home": 1,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------QFNL000100--",
    "sport": "Football",
    "discipline": "Men's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "Bordeaux Stadium",
      "city": "Bordeaux"
    },
    "kickoff": "2024-08-02T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "France",
      "away": "Argentina"
    },
    "score": {
      "home": 1,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------QFNL000300--",
    "sport": "Football",
    "discipline": "Women's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-08-03T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "United States",
      "away": "Japan"
    },
    "score": {
      "home": 1,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------QFNL000200--",
    "sport": "Football",
    "discipline": "Women's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-08-03T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "Spain",
      "away": "Colombia"
    },
    "score": {
      "home": 2,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------QFNL000400--",
    "sport": "Football",
    "discipline": "Women's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-08-03T19:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "Canada",
      "away": "Germany"
    },
    "score": {
      "home": 0,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------QFNL000100--",
    "sport": "Football",
    "discipline": "Women's Quarter-final",
    "round": "Quarter-final",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-08-03T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Quarter-final"
    },
    "teams": {
      "home": "France",
      "away": "Brazil"
    },
    "score": {
      "home": 0,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------SFNL000200--",
    "sport": "Football",
    "discipline": "Men's Semi-final",
    "round": "Semi-final",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-08-05T18:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Semi-final"
    },
    "teams": {
      "home": "Morocco",
      "away": "Spain"
    },
    "score": {
      "home": 1,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------SFNL000100--",
    "sport": "Football",
    "discipline": "Men's Semi-final",
    "round": "Semi-final",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-08-05T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Semi-final"
    },
    "teams": {
      "home": "France",
      "away": "Egypt"
    },
    "score": {
      "home": 3,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------SFNL000200--",
    "sport": "Football",
    "discipline": "Women's Semi-final",
    "round": "Semi-final",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-08-06T18:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Semi-final"
    },
    "teams": {
      "home": "United States",
      "away": "Germany"
    },
    "score": {
      "home": 1,
      "away": 0,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------SFNL000100--",
    "sport": "Football",
    "discipline": "Women's Semi-final",
    "round": "Semi-final",
    "venue": {
      "name": "Marseille Stadium",
      "city": "Marseille"
    },
    "kickoff": "2024-08-06T21:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Semi-final"
    },
    "teams": {
      "home": "Brazil",
      "away": "Spain"
    },
    "score": {
      "home": 4,
      "away": 2,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------FNL-000200--",
    "sport": "Football",
    "discipline": "Men's Bronze Medal Match",
    "round": "Gold Medal Match",
    "venue": {
      "name": "La Beaujoire Stadium",
      "city": "Nantes"
    },
    "kickoff": "2024-08-08T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Gold Medal Match"
    },
    "teams": {
      "home": "Egypt",
      "away": "Morocco"
    },
    "score": {
      "home": 0,
      "away": 6,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------FNL-000200--",
    "sport": "Football",
    "discipline": "Women's Bronze Medal Match",
    "round": "Gold Medal Match",
    "venue": {
      "name": "Lyon Stadium",
      "city": "Lyon"
    },
    "kickoff": "2024-08-09T15:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Gold Medal Match"
    },
    "teams": {
      "home": "Spain",
      "away": "Germany"
    },
    "score": {
      "home": 0,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLMTEAM11------------FNL-000100--",
    "sport": "Football",
    "discipline": "Men's Gold Medal Match",
    "round": "Gold Medal Match",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-08-09T18:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Gold Medal Match"
    },
    "teams": {
      "home": "France",
      "away": "Spain"
    },
    "score": {
      "home": 3,
      "away": 5,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  },
  {
    "id": "FBLWTEAM11------------FNL-000100--",
    "sport": "Football",
    "discipline": "Women's Gold Medal Match",
    "round": "Gold Medal Match",
    "venue": {
      "name": "Parc des Princes",
      "city": "Paris"
    },
    "kickoff": "2024-08-10T17:00:00+02:00",
    "status": "FT",
    "competition": {
      "name": "Paris 2024 Olympics",
      "season": "2024",
      "round": "Gold Medal Match"
    },
    "teams": {
      "home": "Brazil",
      "away": "United States"
    },
    "score": {
      "home": 0,
      "away": 1,
      "halfTime": null
    },
    "scorers": [],
    "lineups": {
      "home": null,
      "away": null
    }
  }
]
